# .goreleaser.yaml
version: 2
project_name: powertrack-cli

# Tell GoReleaser to treat our script as a pre-built binary
builds:
  - id: powertrack
    builder: prebuilt
    binary: powertrack
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    prebuilt:
      path: powertrack.py

nfpms:
  - id: powertrack-cli
    package_name: powertrack-cli
    vendor: Sohanuzzaman3301
    homepage: https://github.com/Sohanuzzaman3301/powertrack-cli
    maintainer: Sohanuzzaman3301 <sohanuzzaman3301@github.com>
    description: A vibrant rainbow battery and power monitor for Linux.
    license: MIT
    formats:
      - deb
      - rpm
    contents:
      - src: powertrack.py
        dst: /usr/bin/powertrack
        file_info:
          mode: 0755

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: README.md
      - src: LICENSE

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
