[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "powertrack-cli"
version = "1.0.4"
authors = [
  { name="Sohanuzzaman3301", email="sohanuzzaman3301@github.com" },
]
description = "A vibrant rainbow battery and power monitor for Linux terminal"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Environment :: Console",
]

[project.urls]
"Homepage" = "https://github.com/Sohanuzzaman3301/powertrack-cli"
"Bug Tracker" = "https://github.com/Sohanuzzaman3301/powertrack-cli/issues"

[project.scripts]
powertrack = "powertrack:main"
